### ISSUE TITLE
Selecting all the text and then scrolling will cause an error: Null check operator used on a null value

### ISSUE THREAD

**Issue by wilinz** [asjqkkkk/markdown_widget#122]
**Describe the bug**
Selecting all the text and then scrolling will cause an error: Null check operator used on a null value

**To Reproduce**
1. long press
2. select all
3. Scroll

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
Please use `flutter doctor -v` to show your flutter environment, and add your `markdown_widget` version too

**Platform**
Android

**Source data**
[https://github.com/wilinz/flutter_markdown_demo](https://github.com/wilinz/flutter_markdown_demo)

**Comment by wilinz** [comment]
https://github.com/asjqkkkk/markdown_widget/assets/59408438/87edb5ed-3189-4ec3-aa33-0fdbad5dd305

**Comment by wilinz** [comment]
`
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#7f1ea](dirty, state: _OverlayEntryWidgetState#d9246):
Null check operator used on a null value

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///C:/Users/wilinz/Desktop/gitee/flutter_markdown/lib/main.dart:18:12
When the exception was thrown, this was the stack: 
#0      SelectableRegionState.startGlyphHeight (package:flutter/src/widgets/selectable_region.dart:1028:56)
#1      SelectableRegionState.contextMenuAnchors (package:flutter/src/widgets/selectable_region.dart:912:25)
#2      new AdaptiveTextSelectionToolbar.selectableRegion (package:flutter/src/material/adaptive_text_selection_toolbar.dart:169:40)
#3      SelectionArea._defaultContextMenuBuilder (package:flutter/src/material/selection_area.dart:96:41)
#4      SelectableRegionState._showToolbar.<anonymous closure> (package:flutter/src/widgets/selectable_region.dart:769:42)
#5      SelectionOverlay.showToolbar.<anonymous closure> (package:flutter/src/widgets/text_selection.dart:1347:36)
#6      ContextMenuController.show.<anonymous closure> (package:flutter/src/widgets/context_menu_controller.dart:65:54)
#7      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:345:36)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198:27)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086:15)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:4805:7)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780:19)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903:21)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358:5)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284:15)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214:9)
#17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072:5)
#18     _invoke (dart:ui/hooks.dart:142:13)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359:5)
#20     _drawFrame (dart:ui/hooks.dart:112:31)
====================================================================================================
Lost connection to device.
`

**Comment by asjqkkkk** [comment]
Hi @wilinz , I thinks this is not a bug of `markdown_widget`, you should remove the `Expanded` inside the `Padding`.

**Comment by Easy-AI-1688** [comment]
This is a bug in Flutter. Please upgrade Flutter to the latest version and this issue will be resolved.
